-- 코드를 입력하세요
WITH RECURSIVE A(HOUR) AS 
(
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 FROM A WHERE HOUR < 23
)
SELECT A.HOUR AS HOUR, COUNT(AO.ANIMAL_ID) AS COUNT
FROM A LEFT JOIN ANIMAL_OUTS AO ON A.HOUR = HOUR(AO.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;