-- 코드를 입력하세요
SELECT BK.BOOK_ID, AU.AUTHOR_NAME, DATE_FORMAT(BK.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK BK JOIN AUTHOR AU ON BK.AUTHOR_ID = AU.AUTHOR_ID
WHERE BK.CATEGORY = '경제'
ORDER BY BK.PUBLISHED_DATE;