-- 코드를 입력하세요
SELECT DISTINCT CC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH ON CC.CAR_ID = RH.CAR_ID
WHERE CC.CAR_TYPE = '세단' AND START_DATE LIKE '2022-10-%'
ORDER BY CAR_ID DESC;